# fly.toml app configuration file generated for idx-keepalive on 2025-12-13T06:09:14+04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'idx-keepalive'
primary_region = 'iad'

[build]

[env]
  PING_INTERVAL_MS = '300000'
  HEADLESS = 'true'
  COOKIES_FILE = '/data/cookies.json'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = false
  min_machines_running = 1

  [[http_service.checks]]
    interval = '60s'
    timeout = '10s'
    grace_period = '30s'
    method = 'GET'
    path = '/health'

[mounts]
  source = "idx_cookies"
  destination = "/data"

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
